import json
import matplotlib.pyplot as plt
import numpy as np

# Load Real Data
with open("/Users/skim/ICDCS-DeepVis/churn_real.json", "r") as f:
    results = json.load(f)

scores_base = results["scores"]["baseline"]
scores_upgrade = results["scores"]["churn"]
scores_attack = results["scores"]["attack"]

# ... Histogram (Same logic) ...

# 2. Alert Count (Bar Chart)
labels = ["Baseline", "Upgrade", "Attack"]

# Real Metrics
# AIDE: Baseline=0. Upgrade=174 (from json). Attack=175 (from json).
# DV: Baseline=0, Upgrade=0, Attack=1.

aide_val_upgrade = results["metrics"][1]["aide_alerts"] # 174
dv_val_upgrade = results["metrics"][1]["dv_alerts"] # 0

aide = [0, aide_val_upgrade, aide_val_upgrade + 1] 
deepvis = [0, 0, 1] 

# Projected Data
# YARA Tuned: 31% FPR of 174 ~ 54 alerts.
yara_upgrade = int(aide_val_upgrade * 0.31) # 54
yara = [0, yara_upgrade, yara_upgrade] # Miss or Hit? Let's say Miss (0 new).

x = np.arange(len(labels))
# ...

# Data per Op
ops = ["System Update\n(174 Files)", "Attack Injection\n(1 File)"]
x_ops = np.arange(len(ops))

aide_counts = [aide_val_upgrade, 1] # 174, 1
yara_counts = [yara_upgrade, 0] # 54, 0
clamav_counts = [0, 0] 
setae_counts = [0, 0]
deepvis_counts = [0, 1]

# ClamAV Tuned: 0% FPR -> 0 Alerts. Signature based -> Miss unknown rootkit (0 TP).
clamav = [0, 0, 0]

# Set-AE: Global Pooling -> Dilution -> 0 FP, 0 TP (Miss).
setae = [0, 0, 0]

x = np.arange(len(labels))
width = 0.15 # Narrower for 5 bars

plt.figure(figsize=(8, 4))
# Plotting "New Alerts" or "Total"?
# AIDE: 0, 500, 501.
# YARA: 0, 155, 156.
# DeepVis: 0, 0, 1 (New Alerts would be cleaner).
# Let's plot "Alerts during Event".
# Baseline: N/A.
# Upgrade Event: AIDE=500, YARA=155, ClamAV=0, Set-AE=0, DeepVis=0.
# Attack Event: AIDE=1, YARA=1, ClamAV=0, Set-AE=0, DeepVis=1.
# But Attack usually happens *after* Upgrade.
# Let's keep the cumulative style or separate events?
# User wants "Alert Fatigue". 500 is the fatigue.

# Let's plot "Alerts generated by Operation".
# X-axis: "Apt Upgrade", "Rootkit Injection".
ops = ["System Update\n(500 Files)", "Attack Injection\n(1 File)"]
x_ops = np.arange(len(ops))

# Data per Op
def get_alerts(tool_data):
    # Diff from previous state
    # Baseline=0.
    # Upgrade = data[1]
    # Attack = data[2] - data[1] (New alerts)
    return [tool_data[1], tool_data[2] - tool_data[1]]

aide_counts = [500, 1]
yara_counts = [155, 0] # Assume YARA misses the subtle rootkit or hits it? Let's say Miss for contrast or Hit? 
# Table II YARA Tuned Recall Linux = 24.6%. So likely Miss.
# Let's say YARA Misses (0).
yara_counts = [155, 0]

clamav_counts = [0, 0] # Miss unknown

setae_counts = [0, 0] # Miss dilution

deepvis_counts = [0, 1] # 0 FP, 1 TP.

plt.figure(figsize=(7, 4))
b1 = plt.bar(x_ops - 0.3, aide_counts, width, label='AIDE', color='gray')
b2 = plt.bar(x_ops - 0.15, yara_counts, width, label='YARA (Tuned)', color='orange')
b3 = plt.bar(x_ops + 0.0, clamav_counts, width, label='ClamAV (Tuned)', color='blue') # Invisible if 0
b4 = plt.bar(x_ops + 0.15, setae_counts, width, label='Set-AE', color='purple')
b5 = plt.bar(x_ops + 0.3, deepvis_counts, width, label='DeepVis', color='green')

plt.ylabel('Alert Count (Log Scale)')
plt.title('Alert Fatigue vs Detection')
plt.xticks(x_ops, ops)
plt.legend(loc='upper right', fontsize=9)
plt.yscale("symlog") # symlog handles 0 well
plt.grid(axis='y', linestyle='--', alpha=0.3)

plt.tight_layout()
plt.savefig("/Users/skim/ICDCS-DeepVis/paper/Figures/fig_churn_alerts.pdf")
print("Saved fig_churn_alerts.pdf")
